### ISSUE TITLE
Indentation in "4. Data Standardization" is incorrect...

### ISSUE THREAD

**Issue by ghost** [edenau/ml-in-numpy#1]
Indentation in Python code in "4. Data Standardization" is incorrect.

Currently:
def standardize(data, scaler):
        return (data - scaler.mean) / scaler.std

Should be:
def standardize(data, scaler):
    return (data - scaler.mean) / scaler.std

Only 4 spaces.

**Comment by ghost** [comment]
In the original issue post, the indentation did not show up.  Tried to say that current 'return' line has 8 spaces; only needs 4.

**Comment by edenau** [comment]
Thanks for raising the issue and I have now fixed the indentation.
